### ISSUE TITLE
Latest update to FHDHR breaks Pluto only on plex. I grabbed the code from a few days ago.

### ISSUE THREAD

**Issue by tharris9d** [fHDHR/fHDHR_plugin_origin_plutotv#15]
Windows 11 Plex server.
The fhdhr Ui works fine. When I click play the channels open in VLC and successfully play the content.
However nothing will play in Plex. All the channels load in the guide but nothing will play. Any suggestions?
Thanks, Tom

**Comment by deathbybandaid** [comment]
remove tuner from plex, restart plexmediaserver, refresh your browser, and re-add

**Comment by deathbybandaid** [comment]
If thst doesn't work, set logging to debug and post them here
